debug:
	g++ main.cpp cpu.cpp memcontrol.cpp IOControl.cpp Clock.cpp -o rmDebug -g -std=c++17 -pthread

release:
	g++ main.cpp cpu.cpp memcontrol.cpp IOControl.cpp Clock.cpp -o rmRelease -std=c++17 -pthread

pedantic:
	g++ main.cpp cpu.cpp memcontrol.cpp IOControl.cpp Clock.cpp -o rmPedantic -g -std=c++17 -Wall -pedantic -pthread
